"""
ExpressBet model — multi-leg accumulator bets generated by AI.

Two types:
  1. Daily Express (free) — auto-generated at 15:00 London, 5 legs, odds >= 1.5
  2. Custom Express (PRO) — user picks leagues, number of legs, target avg odds
"""
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, Text
from sqlalchemy.sql import func
from app.core.database import Base


class ExpressBet(Base):
    __tablename__ = "express_bets"

    id = Column(Integer, primary_key=True, index=True)

    # "daily" or "custom"
    express_type = Column(String, nullable=False, default="daily", index=True)

    # For custom: which user requested it (NULL for daily = shared)
    user_id = Column(Integer, nullable=True, index=True)

    # JSON array of legs:
    # [{fixture_id, home_team, away_team, league, match_date,
    #   bet_type, odds, confidence, fonbet_event_id, fonbet_deeplink}]
    legs_json = Column(Text, nullable=False)

    # Computed totals
    total_odds = Column(Float, nullable=False)
    leg_count = Column(Integer, nullable=False)
    avg_confidence = Column(Float, nullable=True)

    # For custom: user's parameters
    target_avg_odds = Column(Float, nullable=True)
    selected_leagues = Column(Text, nullable=True)  # JSON array of league codes

    # Result tracking
    status = Column(String, nullable=False, default="pending")  # pending / won / lost / partial
    correct_legs = Column(Integer, nullable=True)
    is_verified = Column(Boolean, nullable=True, index=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), index=True)
    verified_at = Column(DateTime, nullable=True)
