"""
ExpressBet model — pre-generated menu of accumulator bets.

Types:
  - "menu"   — pre-generated by background job, served from DB
  - "daily"  — legacy daily express (backward compat)
  - "custom" — legacy custom express (backward compat)
"""
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, Text
from sqlalchemy.sql import func
from app.core.database import Base


class ExpressBet(Base):
    __tablename__ = "express_bets"

    id = Column(Integer, primary_key=True, index=True)

    # "menu" (new), "daily" (legacy), "custom" (legacy)
    express_type = Column(String, nullable=False, default="menu", index=True)

    # Menu preset identification
    preset_name = Column(String, nullable=True, index=True)       # e.g. "daily_safe", "pro_3legs", "league_sa"
    preset_label = Column(String, nullable=True)                   # e.g. "Safe Express"
    preset_description = Column(String, nullable=True)             # e.g. "Low risk, steady odds"
    is_pro_only = Column(Boolean, nullable=False, default=False, index=True)

    # For bookmarked/saved: which user saved it (NULL for menu = shared)
    user_id = Column(Integer, nullable=True, index=True)

    # JSON array of legs
    legs_json = Column(Text, nullable=False)

    # Computed totals
    total_odds = Column(Float, nullable=False)
    leg_count = Column(Integer, nullable=False)
    avg_confidence = Column(Float, nullable=True)

    # Generation parameters
    target_avg_odds = Column(Float, nullable=True)
    selected_leagues = Column(Text, nullable=True)  # JSON array of league codes

    # Result tracking
    status = Column(String, nullable=False, default="pending")  # pending / won / lost / partial
    correct_legs = Column(Integer, nullable=True)
    is_verified = Column(Boolean, nullable=True, index=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), index=True)
    verified_at = Column(DateTime, nullable=True)
