"""
Express Bet API — pre-generated menu of accumulator bets.

All endpoints serve from DB (pre-generated by background job).
No real-time Fonbet API calls = no timeouts, no 500s.
"""
import logging
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import get_current_user
from app.core.database import get_db
from app.models.user import User

logger = logging.getLogger(__name__)
router = APIRouter()


# ---------------------------------------------------------------------------
# Lazy imports
# ---------------------------------------------------------------------------

def _get_generator():
    from app.services.express_generator import (
        get_menu_expresses,
        get_menu_express_by_preset,
        get_today_daily_express,
        get_user_expresses,
        get_available_leagues,
        generate_menu_batch,
    )
    return {
        "get_menu": get_menu_expresses,
        "get_preset": get_menu_express_by_preset,
        "get_today": get_today_daily_express,
        "get_user": get_user_expresses,
        "get_leagues": get_available_leagues,
        "generate_batch": generate_menu_batch,
    }


async def _get_user_from_token(current_user: dict, db: AsyncSession) -> User:
    user_id = current_user.get("user_id")
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid token")
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/menu")
async def get_express_menu(
    current_user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Get today's menu of pre-generated expresses.
    Free users see free presets only. PRO users see all.
    """
    try:
        gen = _get_generator()
    except Exception as e:
        logger.error(f"Express generator import failed: {e}")
        raise HTTPException(status_code=503, detail="Express service temporarily unavailable")

    # Check if user is PRO
    user = await _get_user_from_token(current_user, db)
    is_pro = user.is_premium or (user.funnel == "funnel-2")

    try:
        expresses = await gen["get_menu"](include_pro=is_pro)
    except Exception as e:
        logger.error(f"Failed to fetch express menu: {e}")
        raise HTTPException(status_code=500, detail="Failed to load express menu")

    if not expresses:
        # Try to generate on first request if nothing exists
        try:
            logger.info("No menu expresses found, triggering batch generation...")
            await gen["generate_batch"]()
            expresses = await gen["get_menu"](include_pro=is_pro)
        except Exception as e:
            logger.error(f"On-demand generation failed: {e}")

    return {
        "expresses": expresses or [],
        "is_pro": is_pro,
    }


@router.get("/preset/{preset_name}")
async def get_express_preset(
    preset_name: str,
    current_user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get a specific preset express by name."""
    try:
        gen = _get_generator()
    except Exception as e:
        logger.error(f"Express generator import failed: {e}")
        raise HTTPException(status_code=503, detail="Express service temporarily unavailable")

    express = await gen["get_preset"](preset_name)
    if not express:
        raise HTTPException(status_code=404, detail=f"Preset '{preset_name}' not available")

    # Check PRO access
    if express.get("is_pro_only"):
        user = await _get_user_from_token(current_user, db)
        is_pro = user.is_premium or (user.funnel == "funnel-2")
        if not is_pro:
            raise HTTPException(status_code=403, detail="PRO subscription required")

    return express


@router.get("/daily")
async def daily_express(
    current_user: dict = Depends(get_current_user),
):
    """Get today's daily express (backward compatible — returns daily_value preset)."""
    try:
        gen = _get_generator()
    except Exception as e:
        logger.error(f"Express generator import failed: {e}")
        raise HTTPException(status_code=503, detail="Express service temporarily unavailable")

    try:
        express = await gen["get_today"]()
    except Exception as e:
        logger.error(f"Failed to fetch daily express: {e}")
        express = None

    if not express:
        # Try batch generation
        try:
            await gen["generate_batch"]()
            express = await gen["get_today"]()
        except Exception as e:
            logger.error(f"On-demand generation failed: {e}")

    if not express:
        raise HTTPException(
            status_code=404,
            detail="No daily express available yet. Matches may not be scheduled for today.",
        )

    return express


@router.get("/history")
async def express_history(
    limit: int = 10,
    current_user: dict = Depends(get_current_user),
):
    """Get user's express bet history."""
    user_id = current_user.get("user_id")
    try:
        gen = _get_generator()
        return await gen["get_user"](user_id, limit=limit)
    except Exception as e:
        logger.error(f"Express history failed: {e}")
        return []


@router.get("/leagues")
async def available_leagues(
    current_user: dict = Depends(get_current_user),
):
    """Get available leagues for express."""
    try:
        from app.services.fonbet_api import TOP_LEAGUE_IDS
        return {
            "leagues": [
                {"code": info["code"], "name": info["name"], "league_id": info["league_id"]}
                for info in TOP_LEAGUE_IDS.values()
            ]
        }
    except Exception as e:
        logger.error(f"Leagues endpoint failed: {e}")
        return {"leagues": []}
